version: '3.8'

services:
  flaskgif:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskgif
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=gif-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=flaskdb
      - DATABASE_USER=yuvalbenar
      - DATABASE_PASSWORD=password
    depends_on:
      - gif-db
    networks:
      - flaskapp-network

  gif-db:
    image: mysql:5.7
    container_name: gif-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: yuvalbenar
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - flaskapp-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  flaskapp-network:
    driver: bridge

volumes:
  mysql-data:
